version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'next-playground-postgres'
    restart: 'always'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - 'next-playground-postgres-data:/var/lib/postgresql/data'

  mailcatcher:
    container_name: 'next-playground-mailcatcher'
    image: 'sj26/mailcatcher'
    restart: 'always'
    ports:
      - '1025:1025'
      - '1080:1080'

volumes:
  next-playground-postgres-data:
